import { Duration } from '@jeditrader/providers';

export const lods = [
	{ ms: new Duration(200_000, 'year').ms(), step: new Duration(100_000, 'year') },
	{ ms: new Duration(100_000, 'year').ms(), step: new Duration(50_000, 'year') },
	{ ms: new Duration(20_000, 'year').ms(), step: new Duration(10_000, 'year') },
	{ ms: new Duration(10_000, 'year').ms(), step: new Duration(5_000, 'year') },
	{ ms: new Duration(2_000, 'year').ms(), step: new Duration(1_000, 'year') },
	{ ms: new Duration(1_000, 'year').ms(), step: new Duration(500, 'year') },
	{ ms: new Duration(200, 'year').ms(), step: new Duration(100, 'year') },
	{ ms: new Duration(100, 'year').ms(), step: new Duration(50, 'year') },
	{ ms: new Duration(50, 'year').ms(), step: new Duration(25, 'year') },
	{ ms: new Duration(20, 'year').ms(), step: new Duration(10, 'year') },
	{ ms: new Duration(10, 'year').ms(), step: new Duration(5, 'year') },
	{ ms: new Duration(5, 'year').ms(), step: new Duration(1, 'year') },
	{ ms: new Duration(1, 'year').ms(), step: new Duration(6, 'month') },
	{ ms: new Duration(8, 'month').ms(), step: new Duration(3, 'month') },
	{ ms: new Duration(2, 'month').ms(), step: new Duration(1, 'month') },
	{ ms: new Duration(2, 'week').ms(), step: new Duration(1, 'week') },
	{ ms: new Duration(2, 'day').ms(), step: new Duration(1, 'day') },
	{ ms: new Duration(12, 'hour').ms(), step: new Duration(6, 'hour') },
	{ ms: new Duration(4, 'hour').ms(), step: new Duration(2, 'hour') },
	{ ms: new Duration(2, 'hour').ms(), step: new Duration(1, 'hour') },
	{ ms: new Duration(60, 'minute').ms(), step: new Duration(30, 'minute') },
	{ ms: new Duration(30, 'minute').ms(), step: new Duration(15, 'minute') },
	{ ms: new Duration(10, 'minute').ms(), step: new Duration(5, 'minute') },
	{ ms: new Duration(5, 'minute').ms(), step: new Duration(1, 'minute') },
	{ ms: new Duration(20, 'second').ms(), step: new Duration(10, 'second') },
	{ ms: new Duration(10, 'second').ms(), step: new Duration(5, 'second') },
	{ ms: new Duration(5, 'second').ms(), step: new Duration(1, 'second') },
	{ ms: new Duration(200, 'millisecond').ms(), step: new Duration(100, 'millisecond') },
	{ ms: new Duration(100, 'millisecond').ms(), step: new Duration(50, 'millisecond') },
	{ ms: new Duration(50, 'millisecond').ms(), step: new Duration(25, 'millisecond') },
	{ ms: new Duration(20, 'millisecond').ms(), step: new Duration(10, 'millisecond') },
	{ ms: new Duration(10, 'millisecond').ms(), step: new Duration(5, 'millisecond') },
	{ ms: new Duration(5, 'millisecond').ms(), step: new Duration(1, 'millisecond') },
	{ ms: new Duration(200, 'microsecond').ms(), step: new Duration(100, 'microsecond') },
	{ ms: new Duration(100, 'microsecond').ms(), step: new Duration(50, 'microsecond') },
	{ ms: new Duration(50, 'microsecond').ms(), step: new Duration(25, 'microsecond') },
	{ ms: new Duration(20, 'microsecond').ms(), step: new Duration(10, 'microsecond') },
	{ ms: new Duration(10, 'microsecond').ms(), step: new Duration(5, 'microsecond') },
	{ ms: new Duration(5, 'microsecond').ms(), step: new Duration(1, 'microsecond') },
	{ ms: new Duration(200, 'nanosecond').ms(), step: new Duration(100, 'nanosecond') },
	{ ms: new Duration(100, 'nanosecond').ms(), step: new Duration(50, 'nanosecond') },
	{ ms: new Duration(50, 'nanosecond').ms(), step: new Duration(25, 'nanosecond') },
	{ ms: new Duration(20, 'nanosecond').ms(), step: new Duration(10, 'nanosecond') },
	{ ms: new Duration(10, 'nanosecond').ms(), step: new Duration(5, 'nanosecond') },
	{ ms: 0, step: new Duration(1, 'nanosecond') },
];

