import { Duration } from '@jeditrader/providers';

export const lods = [
	{ ms: new Duration(200_000, 'years').ms(), step: new Duration(100_000, 'years') },
	{ ms: new Duration(100_000, 'years').ms(), step: new Duration(50_000, 'years') },
	{ ms: new Duration(20_000, 'years').ms(), step: new Duration(10_000, 'years') },
	{ ms: new Duration(10_000, 'years').ms(), step: new Duration(5_000, 'years') },
	{ ms: new Duration(2_000, 'years').ms(), step: new Duration(1_000, 'years') },
	{ ms: new Duration(1_000, 'years').ms(), step: new Duration(500, 'years') },
	{ ms: new Duration(200, 'years').ms(), step: new Duration(100, 'years') },
	{ ms: new Duration(100, 'years').ms(), step: new Duration(50, 'years') },
	{ ms: new Duration(50, 'years').ms(), step: new Duration(25, 'years') },
	{ ms: new Duration(20, 'years').ms(), step: new Duration(10, 'years') },
	{ ms: new Duration(10, 'years').ms(), step: new Duration(5, 'years') },
	{ ms: new Duration(5, 'years').ms(), step: new Duration(1, 'years') },
	{ ms: new Duration(1, 'years').ms(), step: new Duration(6, 'months') },
	{ ms: new Duration(8, 'months').ms(), step: new Duration(3, 'months') },
	{ ms: new Duration(2, 'months').ms(), step: new Duration(1, 'months') },
	{ ms: new Duration(2, 'weeks').ms(), step: new Duration(1, 'weeks') },
	{ ms: new Duration(2, 'days').ms(), step: new Duration(1, 'days') },
	{ ms: new Duration(12, 'hours').ms(), step: new Duration(6, 'hours') },
	{ ms: new Duration(4, 'hours').ms(), step: new Duration(2, 'hours') },
	{ ms: new Duration(2, 'hours').ms(), step: new Duration(1, 'hours') },
	{ ms: new Duration(60, 'minutes').ms(), step: new Duration(30, 'minutes') },
	{ ms: new Duration(30, 'minutes').ms(), step: new Duration(15, 'minutes') },
	{ ms: new Duration(10, 'minutes').ms(), step: new Duration(5, 'minutes') },
	{ ms: new Duration(5, 'minutes').ms(), step: new Duration(1, 'minutes') },
	{ ms: new Duration(20, 'seconds').ms(), step: new Duration(10, 'seconds') },
	{ ms: new Duration(10, 'seconds').ms(), step: new Duration(5, 'seconds') },
	{ ms: new Duration(5, 'seconds').ms(), step: new Duration(1, 'seconds') },
	{ ms: new Duration(200, 'milliseconds').ms(), step: new Duration(100, 'milliseconds') },
	{ ms: new Duration(100, 'milliseconds').ms(), step: new Duration(50, 'milliseconds') },
	{ ms: new Duration(50, 'milliseconds').ms(), step: new Duration(25, 'milliseconds') },
	{ ms: new Duration(20, 'milliseconds').ms(), step: new Duration(10, 'milliseconds') },
	{ ms: new Duration(10, 'milliseconds').ms(), step: new Duration(5, 'milliseconds') },
	{ ms: new Duration(5, 'milliseconds').ms(), step: new Duration(1, 'milliseconds') },
	{ ms: new Duration(200, 'microseconds').ms(), step: new Duration(100, 'microseconds') },
	{ ms: new Duration(100, 'microseconds').ms(), step: new Duration(50, 'microseconds') },
	{ ms: new Duration(50, 'microseconds').ms(), step: new Duration(25, 'microseconds') },
	{ ms: new Duration(20, 'microseconds').ms(), step: new Duration(10, 'microseconds') },
	{ ms: new Duration(10, 'microseconds').ms(), step: new Duration(5, 'microseconds') },
	{ ms: new Duration(5, 'microseconds').ms(), step: new Duration(1, 'microseconds') },
	{ ms: new Duration(200, 'nanoseconds').ms(), step: new Duration(100, 'nanoseconds') },
	{ ms: new Duration(100, 'nanoseconds').ms(), step: new Duration(50, 'nanoseconds') },
	{ ms: new Duration(50, 'nanoseconds').ms(), step: new Duration(25, 'nanoseconds') },
	{ ms: new Duration(20, 'nanoseconds').ms(), step: new Duration(10, 'nanoseconds') },
	{ ms: new Duration(10, 'nanoseconds').ms(), step: new Duration(5, 'nanoseconds') },
	{ ms: 0, step: new Duration(1, 'nanoseconds') },
];

